### ISSUE TITLE
Mysterious crash

### ISSUE THREAD

**Issue by BBoldt** [iLexiconn/LifeGauge#1]
https://gist.github.com/395388927d6e12030027

**Comment by iLexiconn** [comment]
Welp, I guess nobody ever used this mod before. I'll fix is right now.

**Comment by iLexiconn** [comment]
0.1.3 fixed the crash, you can download it here: http://minecraft.curseforge.com/projects/lifegauge. :)

**Comment by BBoldt** [comment]
I'm going to have this mod in an experimental pack I'm working on called "The Pioneers"

Thanks for the quick response. :D

https://www.reddit.com/r/feedthebeast/comments/3x8t1j/modpack_idea_i_will_be_working_on_the_pioneers_188/

**Comment by iLexiconn** [comment]
Looks cool! ^.^
